# -*- encoding: utf-8 -*-
namespace :db do
  desc "migrations"
  task :migrate, [] => :environment do

    # { class_name: times }
    # class_name - name of class, which has method perform
    # times - once or forever or never. never - default

    Core::Tasks::Task.registrate!({
      "Core::Tasks::Db::CreateRights" => "forever",
      "Core::Tasks::Db::CreateSuperUser" => "once",
      "Core::Tasks::Db::CreateUndeletableGroups" => "once",
      "Core::Tasks::Db::DeliveryMethod" => "once",
      "Core::Tasks::Db::ExemplarsTypes" => "forever",
      "Core::Tasks::Db::HackedString" => "once",
      "Core::Tasks::Db::RepairRegisters" => "once",
      "Core::Tasks::Db::AddNewOrderType" => "once",
      "Core::Tasks::Db::GroupForList" => "once",
      "Core::Tasks::Db::AddApClassifiers" => "once",
      "Core::Tasks::Db::SetTextFields" => "once",
      "Core::Tasks::Db::GroupsForDdo" => "once",
      "Core::Tasks::Db::SetRegNumberInExemplars" => "once",
      "Core::Tasks::Db::SetYear" => "once",
      "Core::Tasks::Db::LoadOrganizations" => "never",
      "Core::Tasks::Db::LoadOfficials" => "never",
      "Core::Tasks::Db::UpdateParentOrganization" => "once",
      "Core::Tasks::Db::LoadOtherOrganizations" => "never",
      "Core::Tasks::Db::AddFederalDistricts" => "once",
      "Core::Tasks::Db::CreateArchiveGroup" => "once",
      "Core::Tasks::Db::RegistrateQueues" => "forever",
      "Core::Tasks::Db::AddNewThemes" => "once",
      "Core::Tasks::Db::AddYearToControlRecords" => "once",
      "Core::Tasks::Db::UpdateBookNumber" => "once",
      "Core::Tasks::Db::SetNpaSystemCode" => "once",
      "Core::Tasks::Db::GroupForMedo" => "once",
      "Core::Tasks::Db::SetControlTypeText" => "once",
      "Core::Tasks::Db::FixEventRegion" => "once",
      "Core::Tasks::Db::SetUidAndAddressedNameInStatuses" => "once",
      "Core::Tasks::Db::RepairReportModel" => "forever",
      "Core::Tasks::Db::GroupForNpaRegister" => "once",
      "Core::Tasks::Db::SignerForNpaRegister" => "once",
      "Core::Tasks::Db::Help" => "forever",
      "Core::Tasks::Db::RepairPortfolio" => "once",
      "Core::Tasks::Db::RepairPortfolio2" => "once",
      "Core::Tasks::Db::RepairMedoClassifiers" => "once",
      "Core::Tasks::Db::AddRequestTypes" => "once",
      "Core::Tasks::Db::RequestTypesForCitizenRequests" => "once",
      "Core::Tasks::Db::RepairJournalSettings" => "once",
      "Core::Tasks::Db::ArrivedNotRegisteredForCitizenRequests" => "once",
      "Core::Tasks::Db::OrderChangesDocumentTypes" => "once",
      "Core::Tasks::Db::SetSystemCodeForAppealCharacter" => "once",
      "Core::Tasks::Db::AddReportGroups" => "once",
      "Core::Tasks::Db::AddReportGroups2" => "once",
      "Core::Tasks::Db::AddReportGroups3" => "once",
      "Core::Tasks::Db::AddReportGroups4" => "once",
      "Core::Tasks::Db::AddReportGroups5" => "once",
      "Core::Tasks::Db::AddReportGroups6" => "once",
      "Core::Tasks::Db::GroupForReport" => "once",
      "Core::Tasks::Db::CreateIndexes" => "forever",
      "Core::Tasks::Db::AddEmailClassifier" => "once",
      "Core::Tasks::Db::PostfixSettings" => "once",
      "Core::Tasks::Db::SetThemesTexts" => "once",
      "Core::Tasks::Db::ControlSetExternalNumber" => "once",
      "Core::Tasks::Db::CreateMvdSiteMapping" => "once",
      "Core::Tasks::Db::SetSystemCodeForCitizenRequestAppealCharacter" => "once",
      "Core::Tasks::Db::FixMedoIncomingOrders" => "once",
      "Core::Tasks::Db::AddFederalDistrictCrimea" => "once",
      "Core::Tasks::Db::AddCardRegNumber" => "once",
      "Core::Tasks::Db::CreateRegNumbersS" => "once",
      "Core::Tasks::Db::GroupForSecretDocuments" => "once",
      "Core::Tasks::Db::GroupForArchiveRename" => "forever",
      "Core::Tasks::Db::RepairSimpleClassifiers" => "once",
      "Core::Tasks::Db::AddCaModels" => "never",
      "Core::Tasks::Db::ControlSetControlDay" => "once",
      "Core::Tasks::Db::RepairSubthemesNames" => "once",
      "Core::Tasks::Db::AddYears" => "forever",
      "Core::Tasks::Db::AddValuesToClassifiers" => "once",
      "Core::Tasks::Db::DeleteReports" => "once",
      "Core::Tasks::Db::RemoveReportGroups" => "once",
      "Core::Tasks::Db::AddOutgoingDocumentType" => "once",
      "Core::Tasks::Db::RepairCallbacks" => "once",
      "Core::Tasks::Db::AddUnregisteredCount" => "once",
      "Core::Tasks::Db::AddOutgoingDocumentsCharacters" => "once",
      "Core::Tasks::Db::AddRequestResult" => "once",
      "Core::Tasks::Db::RepairRequestResults" => "never",
      "Core::Tasks::Db::AddAttachmentSecrecy" => "once",
      "Core::Tasks::Db::AddRefusalReason" => "once",
      "Core::Tasks::Db::AddOutgoingDocumentsDpdGroup" => "once",
      "Core::Tasks::Db::CreatePostfixSettingsForSecrets" => "once",
      "Core::Tasks::Db::AddCriminalCases" => "once",
      "Core::Tasks::Db::RepairThemesCodes" => "once",
      "Core::Tasks::Db::ResetUsedOrganizations" => "once",
      "Core::Tasks::Db::AddRequestType2" => "once",
      "Core::Tasks::Db::FixReviewResultDefaultValue" => "once",
      "Core::Tasks::Db::FixSubthemes" => "once",
      "Core::Tasks::Db::SetDefaultThemeCode" => "once",
      "Core::Tasks::Db::FixRegisterNumeration" => "once",
      "Core::Tasks::Db::FixAfterFixSubthemes" => "once",
      "Core::Tasks::Db::AddDefaultReviewResult" => "once",
      "Core::Tasks::Db::AddDocumentTypes" => "once",
      "Core::Tasks::Db::AddDefaultResultSupported" => "once",
      "Core::Tasks::Db::ThemeDefaultValuesUpdate" => "once",
      "Core::Tasks::Db::RepairBlockedNumbers" => "once",
      "Core::Tasks::Db::Sub2themeDefaultsFix" => "once",
      "Core::Tasks::Db::CreateNewOutgoingCharacter" => "once",
      "Core::Tasks::Db::CreateIndexesForBlockedNumbers" => "once",
      "Core::Tasks::Db::AddDefaultReviewResult2" => "once",
      "Core::Tasks::Db::MultiplyDocumentTypes" => "once",
      "Core::Tasks::Db::ChangeDocumentTypeName" => "once",
      "Core::Tasks::Db::AddDeclaredDocumentTypes" => "once",
      "Core::Tasks::Db::AddControlTypes" => "once",
      "Core::Tasks::Db::CreateLogIndexes" => "once",
      "Core::Tasks::Db::SetWithDelayFlag" => "once",
      "Core::Tasks::Db::AppealStatusDefaultValue" => "once",
      "Core::Tasks::Db::DdoMvdGroupFix" => "once",
      "Core::Tasks::Db::SstuOshsEsdOrganisation" => "never",
      "Core::Tasks::Db::GroupForPrimaryConsideration" => "once",
      "Core::Tasks::Db::AddNameCityFix" => "once",
      "Core::Tasks::Db::AddOshsEsdDefaultOrganisations" => "once",
      "Core::Tasks::Db::CardsDenormalizerSheme" => "forever",
      "Core::Tasks::Db::ResetNpaSystemCode" => "once",
      "Core::Tasks::Db::CreateIndexesForElasticSearchConstructor" => "once",
      "Core::Tasks::Db::FormatOrderChangesDate" => "once",
      "Core::Tasks::Db::AddDefaultChangeTypes" => "once",
      "Core::Tasks::Db::FederalConstitutionalLaw" => "once",
      "Core::Tasks::Db::FixPageTitle" => "once",
      "Core::Tasks::Db::FixDdoDate" => "once",
      "Core::Tasks::Db::CreateDefaultElasticSearchFields" => "once",
      "Core::Tasks::Db::AddTelegramma" => "once",
      "Core::Tasks::Db::UpdateThumbs" => "once",
      "Core::Tasks::Db::RenameIncomeFormRequestByInternet" => "once",
      "Core::Tasks::Db::UpdateUndeletableSimples" => "once",
      "Core::Tasks::Db::AddNewUndeletableGroup" => "once",
      "Core::Tasks::Db::OshsToElasticSearch" => "once",
      "Core::Tasks::Db::FixSkippedClassifiersIds" => "once",
      "Core::Tasks::Db::UpdateOfficialEmail" => "once",
      "Core::Tasks::Db::AddDefaultGroups" => "forever",
      "Core::Tasks::Db::CopyReceptionDayCitizensArrayToModels" => "once",
      "Core::Tasks::Db::RepairCustomOrganizations" => "once",
      "Core::Tasks::Db::CreateSevastopol" => "once",
      "Core::Tasks::Db::RemoveMembersWithDeletedOfficials" => "once",
      "Core::Tasks::Db::MigrateReceptionAppointers" => "once",
      "Core::Tasks::Db::ReregisteredExemplarStatus" => "once",
      "Core::Tasks::Db::GroupProviderDocuments" => "once",
      "Core::Tasks::Db::RenameOutgoingDocumentsDpdGroup" => "once",
      "Core::Tasks::Db::RepairElasticControlDate" => "once",
      "Core::Tasks::Db::RemoveIncomingDocumentsTypes" => "once",
      "Core::Tasks::Db::AddRightsToRoles" => "once"
    })

    Core::Tasks::Task.go!

  end
end
